name: Java on macOS
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-run:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'
        
    - name: Build with Maven
      run: mvn package
    - name: Get directory where we are now
      run: |
        pwd
        ls
    - name: Download tf 1
      run: |
        mkdir -p Tensorflow-1.15.0-1.15.0-macosx-x86_64-cpu
        cd Tensorflow-1.15.0-1.15.0-macosx-x86_64-cpu
        wget https://repo1.maven.org/maven2/org/tensorflow/libtensorflow/1.15.0/libtensorflow-1.15.0.jar
        wget https://repo1.maven.org/maven2/org/tensorflow/libtensorflow_jni/1.15.0/libtensorflow_jni-1.15.0.jar
        wget https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.5.1/protobuf-java-3.5.1.jar
        wget https://repo1.maven.org/maven2/org/tensorflow/proto/1.15.0/proto-1.15.0.jar
        wget https://icy-nexus.pasteur.fr/repository/Icy/org/bioimageanalysis/icy/tensor-flow-1-interface/0.0.1/tensor-flow-1-interface-0.0.1.jar
        ls
    - name: Download tf 2
      run: |
        mkdir -p Tensorflow-2.4.1-0.3.3-macosx-x86_64-cpu
        cd Tensorflow-2.4.1-0.3.3-macosx-x86_64-cpu
        wget https://repo1.maven.org/maven2/org/tensorflow/tensorflow-core-api/0.3.3/tensorflow-core-api-0.3.3.jar
        wget https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.8.0/protobuf-java-3.8.0.jar
        wget https://repo1.maven.org/maven2/org/tensorflow/ndarray/0.3.3/ndarray-0.3.3.jar
        wget https://repo1.maven.org/maven2/org/tensorflow/tensorflow-core-api/0.3.3/tensorflow-core-api-0.3.3-macosx-x86_64.jar
        wget https://repo1.maven.org/maven2/org/bytedeco/javacpp/1.5.4/javacpp-1.5.4.jar
        wget https://repo1.maven.org/maven2/org/bytedeco/javacpp/1.5.4/javacpp-1.5.4-macosx-x86_64.jar
        wget https://icy-nexus.pasteur.fr/repository/Icy/org/bioimageanalysis/icy/tensor-flow-2-interface-0.3.0/0.0.1/tensor-flow-2-interface-0.3.0-0.0.1.jar
        ls
    - name: Run Java file
      run: |
        cd /Users/runner/work/macos-test/macos-test/src/main/java
        pwd
        ls
        javac org/bioimageanalysis/icy/deeplearning/example/ExampleLoadTensorflow1Tensorflow2.java
        ls
        java org/bioimageanalysis/icy/deeplearning/example/ExampleLoadTensorflow1Tensorflow2
