name: Pytorch-DJL on on macOS
on:
  #push:
   # branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-10.15, ubuntu-latest, windows-latest]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '8'
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Get directory where we are now
      run: |
        pwd
    - name: Build with Maven
      run: mvn package
    - name: Get directory where we are now again
      run: |
        pwd
        ls
    - name: Download engines new engine
      shell: bash
      run: |
        mkdir - p engines
        cd engines
        if [[ "$OSTYPE" == "darwin"* ]]; then
          echo "This is running on macOS"
          mkdir - p pytorch-1.13.0-1.13.0-macosx-x86_64-cpu-gpu
          cd pytorch-1.13.0-1.13.0-macosx-x86_64-cpu-gpu
          #cp /Users/runner/work/macos-test/macos-test/dl-modelrunner-pytorch-javacpp-0.2.1-SNAPSHOT.jar .
          curl -O https://repo1.maven.org/maven2/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
          curl -O https://repo1.maven.org/maven2/net/imglib2/imglib2/5.13.0/imglib2-5.13.0.jar
          curl -O https://repo1.maven.org/maven2/ai/djl/pytorch/pytorch-jni/1.12.1-0.21.0/pytorch-jni-1.12.1-0.21.0.jar
          curl -O https://repo1.maven.org/maven2/ai/djl/pytorch/pytorch-engine/0.21.0/pytorch-engine-0.21.0.jar
          curl -O https://repo1.maven.org/maven2/ai/djl/api/0.21.0/api-0.21.0.jar
          curl -O https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar
          curl -O https://maven.scijava.org/content/repositories/releases/io/bioimage/dl-modelrunner-pytorch/0.2.0/dl-modelrunner-pytorch-0.2.0.jar
          curl -O https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar
          curl -O https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
          curl -O https://repo1.maven.org/maven2/org/slf4j/slf4j-api/2.0.6/slf4j-api-2.0.6.jar
        elif [[ "$OSTYPE" == "msys" || "$OSTYPE" == "win32" ]]; then
          echo "This is running on Windows"
          mkdir - p pytorch-1.13.0-1.13.0-windows-x86_64-cpu-gpu
          cd pytorch-1.13.0-1.13.0-windows-x86_64-cpu-gpu
          #cp D:\\a\\macos-test\\macos-test\\dl-modelrunner-pytorch-javacpp-0.2.1-SNAPSHOT.jar .
          curl -O https://repo1.maven.org/maven2/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
          curl -O https://repo1.maven.org/maven2/net/imglib2/imglib2/5.13.0/imglib2-5.13.0.jar
          curl -O https://repo1.maven.org/maven2/ai/djl/pytorch/pytorch-jni/1.12.1-0.19.0/pytorch-jni-1.12.1-0.19.0.jar
          curl -O https://repo1.maven.org/maven2/ai/djl/pytorch/pytorch-engine/0.19.0/pytorch-engine-0.19.0.jar
          curl -O https://repo1.maven.org/maven2/ai/djl/api/0.19.0/api-0.19.0.jar
          curl -O https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar
          curl -O https://maven.scijava.org/content/repositories/releases/io/bioimage/dl-modelrunner-pytorch/0.2.0/dl-modelrunner-pytorch-0.2.0.jar
          curl -O https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar
          curl -O https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
          curl -O https://repo1.maven.org/maven2/org/slf4j/slf4j-api/2.0.6/slf4j-api-2.0.6.jar
        elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
          echo "This is running on Linux"
          mkdir - p pytorch-1.13.0-1.13.0-linux-x86_64-cpu-gpu
          cd pytorch-1.13.0-1.13.0-linux-x86_64-cpu-gpu
          #cp /home/runner/work/macos-test/macos-test/dl-modelrunner-pytorch-javacpp-0.2.1-SNAPSHOT.jar .
          curl -O https://repo1.maven.org/maven2/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
          curl -O https://repo1.maven.org/maven2/net/imglib2/imglib2/5.13.0/imglib2-5.13.0.jar
          curl -O https://repo1.maven.org/maven2/ai/djl/pytorch/pytorch-jni/1.12.1-0.19.0/pytorch-jni-1.12.1-0.19.0.jar
          curl -O https://repo1.maven.org/maven2/ai/djl/pytorch/pytorch-engine/0.19.0/pytorch-engine-0.19.0.jar
          curl -O https://repo1.maven.org/maven2/ai/djl/api/0.19.0/api-0.19.0.jar
          curl -O https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar
          curl -O https://maven.scijava.org/content/repositories/releases/io/bioimage/dl-modelrunner-pytorch/0.2.0/dl-modelrunner-pytorch-0.2.0.jar
          curl -O https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar
          curl -O https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
          curl -O https://repo1.maven.org/maven2/org/slf4j/slf4j-api/2.0.6/slf4j-api-2.0.6.jar
        else
          echo "Unknown OS"
        fi
        pwd
        ls
    - name: Download pt model
      run: |
        mkdir -p modelpt
        cd modelpt
        curl -O https://zenodo.org/api/files/a7eb8d94-9217-4276-8b0d-ff88e1ac78c7/weights-torchscript.pt
        ls
    - name: Build with Maven
      run: mvn package shade:shade
    - name: Run Java file
      shell: bash
      run: |
        # java -jar target/dl-model-runner-0.0.0.jar
        if [[ "$OSTYPE" == "win"* ]]; then
          java -cp  target\\dl-model-runner-0.0.0.jar io.bioimage.modelrunner.example.ExampleLoadAndRunModel
        else
          java -cp  target/dl-model-runner-0.0.0.jar io.bioimage.modelrunner.example.ExampleLoadAndRunModel
        fi
      

