name: Java on macOS
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-run:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'
        
    - name: Build with Maven
      run: mvn package
    - name: Get directory where we are now
      run: |
        pwd
        ls
    - name: Download tf 1
      run: |
        mkdir -p Tensorflow-1.15.0-1.15.0-macosx-x86_64-cpu
        cd Tensorflow-1.15.0-1.15.0-macosx-x86_64-cpu
        wget wget https://repo1.maven.org/maven2/org/tensorflow/libtensorflow/1.15.0/libtensorflow-1.15.0.jar
        wget https://repo1.maven.org/maven2/org/tensorflow/libtensorflow_jni/1.15.0/libtensorflow_jni-1.15.0.jar
        wget https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.5.1/protobuf-java-3.5.1.jar
        wget https://repo1.maven.org/maven2/org/tensorflow/proto/1.15.0/proto-1.15.0.jar
        wget https://icy-nexus.pasteur.fr/repository/Icy/org/bioimageanalysis/icy/tensor-flow-1-interface/0.0.1/tensor-flow-1-interface-0.0.1.jar
        cp /Users/runner/work/macos-test/macos-test/tensor-flow-1-interface-0.0.1.jar /Users/runner/work/macos-test/macos-test/Tensorflow-1.15.0-1.15.0-macosx-x86_64-cpu/ 
        ls
    - name: Download tf 1-aux
      run: |
        mkdir -p Tensorflow-1.15.0-1.15.0-macosx-x86_64-cpu2
        cd Tensorflow-1.15.0-1.15.0-macosx-x86_64-cpu2
        wget https://repo1.maven.org/maven2/org/bytedeco/tensorflow-platform/1.15.5-1.5.8/tensorflow-platform-1.15.5-1.5.8.jar
        wget https://repo1.maven.org/maven2/org/bytedeco/mkl-dnn-platform/0.21.5-1.5.8/mkl-dnn-platform-0.21.5-1.5.8.jar
        wget https://repo1.maven.org/maven2/org/bytedeco/javacpp/1.5.8/javacpp-1.5.8.jar
        wget https://repo1.maven.org/maven2/org/bytedeco/javacpp/1.5.8/javacpp-1.5.8-macosx-x86_64.jar
        wget https://search.maven.org/remotecontent?filepath=org/bytedeco/mkl-dnn/0.21.5-1.5.8/mkl-dnn-0.21.5-1.5.8.jar
        wget https://search.maven.org/remotecontent?filepath=org/bytedeco/mkl-dnn/0.21.5-1.5.8/mkl-dnn-0.21.5-1.5.8-macosx-x86_64.jar
        wget https://repo1.maven.org/maven2/org/bytedeco/tensorflow/1.15.5-1.5.8/tensorflow-1.15.5-1.5.8.jar
        wget https://repo1.maven.org/maven2/org/bytedeco/tensorflow/1.15.5-1.5.8/tensorflow-1.15.5-1.5.8-macosx-x86_64.jar
        wget https://repo1.maven.org/maven2/org/bytedeco/javacpp-platform/1.5.8/javacpp-platform-1.5.8.jar
        cp /Users/runner/work/macos-test/macos-test/tensor-flow-1-interface-0.0.1.jar /Users/runner/work/macos-test/macos-test/Tensorflow-1.15.0-1.15.0-macosx-x86_64-cpu2/ 
        ls
    - name: Download tf 2
      run: |
        mkdir -p Tensorflow-2.4.1-0.3.3-macosx-x86_64-cpu
        cd Tensorflow-2.4.1-0.3.3-macosx-x86_64-cpu
        wget https://repo1.maven.org/maven2/org/tensorflow/tensorflow-core-api/0.3.3/tensorflow-core-api-0.3.3.jar
        wget https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.8.0/protobuf-java-3.8.0.jar
        wget https://repo1.maven.org/maven2/org/tensorflow/ndarray/0.3.3/ndarray-0.3.3.jar
        wget https://repo1.maven.org/maven2/org/tensorflow/tensorflow-core-api/0.3.3/tensorflow-core-api-0.3.3-macosx-x86_64.jar
        wget https://repo1.maven.org/maven2/org/bytedeco/javacpp/1.5.4/javacpp-1.5.4.jar
        wget https://repo1.maven.org/maven2/org/bytedeco/javacpp/1.5.4/javacpp-1.5.4-macosx-x86_64.jar
        wget https://icy-nexus.pasteur.fr/repository/Icy/org/bioimageanalysis/icy/tensor-flow-2-interface-0.3.0/0.0.1/tensor-flow-2-interface-0.3.0-0.0.1.jar
        ls
    - name: Download modeltf1
      run: |
        brew install unzip
        mkdir -p modeltf1
        cd modeltf1
        wget https://zenodo.org/api/files/5a9cfb56-3a5d-4796-986d-8f46b7987b92/tf_weights.zip
        unzip tf_weights.zip
        ls
    - name: Download modeltf2
      run: |
        brew install unzip
        mkdir -p modeltf2
        cd modeltf2
        wget https://github.com/stardist/stardist-icy/raw/main/src/main/resources/models/2D/dsb2018_paper.zip
        unzip dsb2018_paper.zip
        ls
    - name: Build with Maven
      run: mvn package shade:shade
    - name: Run Java file
      run: |
        # java -jar target/dl-model-runner-0.0.0.jar
        java -cp  target/dl-model-runner-0.0.0.jar org.bioimageanalysis.icy.deeplearning.example.ExampleLoadTensorflow1Tensorflow2

