name: DIJ on macOS
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-latest]
        #os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '8'
    - name: Cache weights file
      uses: actions/cache@v2
      with:
        path: weights-torchscript.pt
        key: ${{ runner.os }}-weights-${{ hashFiles('**/weights-torchscript.pt') }}
        restore-keys: ${{ runner.os }}-weights-
    - name: Download weights file
      run: |
        if test -f /Users/runner/work/macos-test/macos-test/weights-torchscript.pt; then
            echo "File exists"
        else
            curl -o weights-torchscript.pt https://zenodo.org/api/files/a7eb8d94-9217-4276-8b0d-ff88e1ac78c7/weights-torchscript.pt
        fi
    - name: Cache Fiji file
      uses: actions/cache@v2
      with:
        path: fiji-macosx.zip
        key: ${{ runner.os }}-fiji-${{ hashFiles('**/fiji-macosx.zip') }}
        restore-keys: ${{ runner.os }}-fiji-
    - name: Download Fiji file
      run: | 
        if test -f /Users/runner/work/macos-test/macos-test/fiji-macosx.zip; then
            echo "File exists"
        else
            curl -o fiji-macosx.zip https://downloads.micron.ox.ac.uk/fiji_update/mirrors/fiji-latest/fiji-macosx.zip
        fi
    - name: Download Fiji
      run: |
        brew install unzip
        unzip fiji-macosx.zip
        ls
        cd Fiji.App
        ls
    - name: See contents of fiji folder
      run: ls Fiji.App
    - name: Download pt
      run: |
        mkdir -p Fiji.App/models/modelpt
        cp weights-torchscript.pt Fiji.App/models/modelpt
        cd Fiji.App/models/modelpt
        curl -O https://zenodo.org/api/files/a7eb8d94-9217-4276-8b0d-ff88e1ac78c7/zero_mean_unit_variance.ijm
        curl -O https://bioimage-io.github.io/collection-bioimage-io/rdfs/10.5281/zenodo.6406803/6406804/rdf.yaml
        curl -O https://zenodo.org/api/files/a7eb8d94-9217-4276-8b0d-ff88e1ac78c7/sample_input_0.tif
        ls
    - name: Download tf2
      run: |
        cd Fiji.App
        mkdir -p models/tf2
        cd models/tf2
        curl -o weights-torchscript.pt https://zenodo.org/api/files/a7eb8d94-9217-4276-8b0d-ff88e1ac78c7/weights-torchscript.pt
    - name: Download all engines
      run: |
        cd Fiji.App
        mkdir -p engines
        python /Users/runner/work/macos-test/macos-test/download_engines.py tensorflow 2.7.0
        python /Users/runner/work/macos-test/macos-test/download_engines.py tensorflow 1.15.0
        ls
        cd engines
        ls
    - name: Download engines
      run: |
        cd Fiji.App
        mkdir -p engines
        cd engines
        # python /Users/runner/work/macos-test/macos-test/download_engines.py
        mkdir -p pytorch-1.13.1-1.13.1-macosx-x86_64-cpu
        cd pytorch-1.13.1-1.13.1-macosx-x86_64-cpu
        curl -O https://sandbox.zenodo.org/record/1182168/files/dl-modelrunner-pytorch-javacpp-0.2.1-SNAPSHOT.jar?download=1
        curl -O https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/pytorch-platform/1.13.1-1.5.9-SNAPSHOT/pytorch-platform-1.13.1-1.5.9-20230404.055134-18.jar
        curl -O https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/pytorch/1.13.1-1.5.9-SNAPSHOT/pytorch-1.13.1-1.5.9-20230404.071430-36.jar
        curl -O https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/pytorch/1.13.1-1.5.9-SNAPSHOT/pytorch-1.13.1-1.5.9-20230404.071430-36-macosx-x86_64.jar
        curl -O https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-platform/1.5.9-SNAPSHOT/javacpp-platform-1.5.9-20230409.122134-298.jar
        curl -O https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp/1.5.9-SNAPSHOT/javacpp-1.5.9-20230407.112849-215.jar
        curl -O https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp/1.5.9-SNAPSHOT/javacpp-1.5.9-20230407.112849-215-macosx-x86_64.jar
        curl -O https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/openblas-platform/0.3.23-1.5.9-SNAPSHOT/openblas-platform-0.3.23-1.5.9-20230409.045817-48.jar
        curl -O https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/openblas/0.3.23-1.5.9-SNAPSHOT/openblas-0.3.23-1.5.9-20230404.015544-39.jar
        curl -O https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/openblas/0.3.23-1.5.9-SNAPSHOT/openblas-0.3.23-1.5.9-20230404.015544-39-macosx-x86_64.jar
        ls
    - name: Run model with macro
      run: |
        cp DeepImageJ_-3.0.0.jar /Users/runner/work/macos-test/macos-test/Fiji.App/plugins
        cp dl-modelrunner-0.2.1-SNAPSHOT.jar /Users/runner/work/macos-test/macos-test/Fiji.App/jars
        /Users/runner/work/macos-test/macos-test/Fiji.App/Contents/MacOS/ImageJ-macosx --headless --console -macro /Users/runner/work/macos-test/macos-test/macro.txt

      

