name: download all engines
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-latest, ubuntu-latest, windows-latest]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '8'
    - name: Cache weights file
      uses: actions/cache@v2
      with:
        path: weights-torchscript.pt
        key: ${{ runner.os }}-weights-${{ hashFiles('**/weights-torchscript.pt') }}
        restore-keys: ${{ runner.os }}-weights-
    - name: Download all engines
      run: |
        python /Users/runner/work/macos-test/macos-test/download_engines.py tensorflow
        cd engines
        ls
    