name: DIJ on macOS
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        #os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '8'
    - name: Download Fiji
      run: |
        brew install unzip
        curl -O https://downloads.micron.ox.ac.uk/fiji_update/mirrors/fiji-latest/fiji-macosx.zip
        unzip fiji-macosx.zip
        ls
        cd Fiji.App
        ls
    - name: See contents of fiji folder
      run: ls Fiji.App
    - name: Download pt
      run: |
        cd Fiji.App
        mkdir -p models/modelpt
        cd models/modelpt
        curl -O https://zenodo.org/api/files/a6d65a8b-4fed-453f-89f6-515a2a73a99e/weights-torchscript.pt
        curl -O https://zenodo.org/api/files/a6d65a8b-4fed-453f-89f6-515a2a73a99e/sample_input_0.tif
        curl -O https://bioimage-io.github.io/collection-bioimage-io/rdfs/10.5281/zenodo.5874741/5874742/rdf.yaml
        curl -O https://zenodo.org/api/files/a6d65a8b-4fed-453f-89f6-515a2a73a99e/zero_mean_unit_variance.ijm
        ls
    - name: Download engines
      run: |
        cd Fiji.App
        mkdir -p engines
        cd engines
        #python /Users/runner/work/macos-test/macos-test/download_engines.py
        mkdir -p pytorch-1.13.1-1.13.1-macosx-x86_64-cpu
        cd pytorch-1.13.1-1.13.1-macosx-x86_64-cpu
        curl -O https://repo1.maven.org/maven2/ai/djl/pytorch/pytorch-jni/1.13.0-0.20.0/pytorch-jni-1.13.0-0.20.0.jar
        curl -O https://repo1.maven.org/maven2/ai/djl/pytorch/pytorch-engine/0.20.0/pytorch-engine-0.20.0.jar
        curl -O https://repo1.maven.org/maven2/ai/djl/api/0.20.0/api-0.20.0.jar
        curl -O https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar
        curl -O https://maven.scijava.org/content/repositories/releases/io/bioimage/dl-modelrunner-pytorch/0.2.0/dl-modelrunner-pytorch-0.2.0.jar
        curl -O https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar
        curl -O https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
        curl -O https://repo1.maven.org/maven2/org/slf4j/slf4j-api/2.0.6/slf4j-api-2.0.6.jar
    - name: Run model with macro
      run: |
        cp DeepImageJ_-3.0.0.jar /Users/runner/work/macos-test/macos-test/Fiji.App/plugins
        /Users/runner/work/macos-test/macos-test/Fiji.App/Contents/MacOS/ImageJ-macosx --headless --console -macro /Users/runner/work/macos-test/macos-test/macro.txt
      

